community-management:
  name: community-management
  version: 1.0.0

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30

logging:
  level:
    com.akai: debug
    org.springframework: warn

spring:
  profiles:
    active:
      - druid
      - redis
  jackson:
    default-property-inclusion: non_null

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis-plus:
  type-aliases-package: com.akai.**.domain
  mapper-locations: classpath:mapper/**/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
  global-config:
    db-config:
      id-type: assign_id
    banner: false

token:
  header: Authorization
  secret: loveshiho
  expireTime: 30
