# ??????
community-management:
  # ??
  name: community-management
  # ??
  version: 1.0.0

# ??????
server:
  #????HTTP??
  port: 8080
  servlet:
    # ???????
    context-path: /
  tomcat:
    # tomcat?URI??
    uri-encoding: UTF-8
    # tomcat?????????200
    max-threads: 800
    # Tomcat?????????????25
    min-spare-threads: 30

# ????
logging:
  level:
    com.akai: debug
    org.springframework: warn

# Spring??
spring:
  profiles:
    active: druid

# MyBatis??

# PageHelper????
pagehelper:
  # ?????
  helperDialect: mysql
  # ????? ??????? true??pageNum<=0 ???????? pageNum>pages???????????????
  reasonable: true
  # ?????????????????????pageNum?pageSize???????????
  supportMethodsArguments: true
  # params?????startPage(Object params)??????????????????????????????
  params: count=countSql

# mybatis-plus??
mybatis-plus:
  # plus??????????????????????????????
  type-aliases-package: com.akai.pojo
  # mybatis  mapper.xml???
  mapper-locations: classpath:mapper/**/*Mapper.xml
  # mybatis  config???????
  config-location: classpath:mybatis/mybatis-config.xml
  # ????
  global-config:
    db-config:
      # id???????id
      id-type: assign_id
    # ???mybatis-plus?banner
    banner: false
